import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Body from "../components/Body";

export default function Home() {
  const [reset, setReset] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative h-screen w-screen overflow-x-hidden bg-black">
        <Header isReset={reset} toggleReset={setReset} />
        <Body isReset={reset} />
      </main>
    </div>
  );
}
